### ISSUE TITLE
npm install failing (error ENOENT)

### ISSUE THREAD

**Issue by mhingston** [blockstack/blockstack-todos#17]
Are there any known issues when installing using npm 5?

node: v8.7.0
npm: 5.5.1
Linux 4.13.8-1 x86_64

`npm install` fails with:

    19834 verbose stack Error: ENOENT: no such file or directory, rename '/home/miles/blockstack-todos/node_modules/.staging/blockstack-05ae9f0d/node_modules/JSONStream' -> '/home/miles/blockstack-todos/node_modules/.staging/JSONStream-a0c1e476'
    19834 verbose stack     at /usr/lib/node_modules/npm/node_modules/move-concurrently/move.js:14:12
    19834 verbose stack     at rename (/usr/lib/node_modules/npm/node_modules/move-concurrently/move.js:74:12)
    19834 verbose stack     at /usr/lib/node_modules/npm/node_modules/move-concurrently/node_modules/run-queue/queue.js:63:24
    19834 verbose stack     at RunQueue._runQueue (/usr/lib/node_modules/npm/node_modules/move-concurrently/node_modules/run-queue/queue.js:62:22)
    19834 verbose stack     at /usr/lib/node_modules/npm/node_modules/move-concurrently/node_modules/run-queue/queue.js:30:12
    19834 verbose stack     at RunQueue.run (/usr/lib/node_modules/npm/node_modules/move-concurrently/node_modules/run-queue/queue.js:27:24)
    19834 verbose stack     at move (/usr/lib/node_modules/npm/node_modules/move-concurrently/move.js:46:16)
    19834 verbose stack     at wrappedMove (/usr/lib/node_modules/npm/lib/utils/move.js:11:10)
    19834 verbose stack     at mkdirp.then (/usr/lib/node_modules/npm/lib/install/action/extract.js:145:14)
    19834 verbose stack     at /usr/lib/node_modules/npm/node_modules/mkdirp/index.js:48:26
    19834 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:287:18
    19834 verbose stack     at FSReqWrap.oncomplete (fs.js:154:5)
    19834 verbose stack     at finishModule (/usr/lib/node_modules/npm/lib/install/action/extract.js:144:42)
    19834 verbose stack     at BB.map.then (/usr/lib/node_modules/npm/lib/install/action/extract.js:137:12)
    19834 verbose stack     at stageBundledModule (/usr/lib/node_modules/npm/lib/install/action/extract.js:136:6)
    19834 verbose stack     at BB.map (/usr/lib/node_modules/npm/lib/install/action/extract.js:109:14)
    19834 verbose stack     at runCallback (timers.js:785:20)
    19834 verbose stack     at tryOnImmediate (timers.js:747:5)
    19834 verbose stack     at processImmediate [as _immediateCallback] (timers.js:718:5)
    19834 verbose stack     at readBundled (/usr/lib/node_modules/npm/lib/install/action/extract.js:104:13)
    19834 verbose stack     at BB.fromNode.then (/usr/lib/node_modules/npm/lib/install/action/extract.js:91:14)
    19834 verbose stack     at extract (/usr/lib/node_modules/npm/lib/install/action/extract.js:89:6)
    19834 verbose stack     at BB.fromNode (/usr/lib/node_modules/npm/lib/install/actions.js:75:20)
    19834 verbose stack     at runAction (/usr/lib/node_modules/npm/lib/install/actions.js:74:13)
    19834 verbose stack     at isInstallable.then (/usr/lib/node_modules/npm/lib/install/actions.js:54:16)
    19834 verbose stack     at runCallback (timers.js:785:20)
    19834 verbose stack     at tryOnImmediate (timers.js:747:5)
    19834 verbose stack     at processImmediate [as _immediateCallback] (timers.js:718:5)
    19834 verbose stack     at actions.(anonymous function) (/usr/lib/node_modules/npm/lib/install/actions.js:52:44)
    19834 verbose stack     at execAction (/usr/lib/node_modules/npm/lib/install/actions.js:198:18)
    19834 verbose stack     at result.then (/usr/lib/node_modules/npm/lib/install/actions.js:77:25)
    19834 verbose stack     at withInit (/usr/lib/node_modules/npm/lib/install/actions.js:132:15)
    19834 verbose stack     at runCallback (timers.js:785:20)
    19834 verbose stack     at withInit (/usr/lib/node_modules/npm/lib/install/actions.js:182:13)
    19834 verbose stack     at doParallel (/usr/lib/node_modules/npm/lib/install/actions.js:131:10)
    19834 verbose stack     at Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    19834 verbose stack     at LOOP (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    19834 verbose stack     at /usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
    19834 verbose stack     at next (/usr/lib/node_modules/npm/node_modules/rimraf/rimraf.js:75:7)
    19834 verbose stack     at CB (/usr/lib/node_modules/npm/node_modules/rimraf/rimraf.js:111:9)
    19834 verbose stack     at /usr/lib/node_modules/npm/node_modules/rimraf/rimraf.js:137:14
    19834 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:284:29
    19834 verbose stack     at FSReqWrap.oncomplete (fs.js:153:21)
    19834 verbose stack From previous event:
    19834 verbose stack     at runAction (/usr/lib/node_modules/npm/lib/install/actions.js:74:13)
    19834 verbose stack     at isInstallable.then (/usr/lib/node_modules/npm/lib/install/actions.js:54:16)
    19834 verbose stack     at runCallback (timers.js:785:20)
    19834 verbose stack     at tryOnImmediate (timers.js:747:5)
    19834 verbose stack     at processImmediate [as _immediateCallback] (timers.js:718:5)
    19834 verbose stack From previous event:
    19834 verbose stack     at actions.(anonymous function) (/usr/lib/node_modules/npm/lib/install/actions.js:52:44)
    19834 verbose stack     at execAction (/usr/lib/node_modules/npm/lib/install/actions.js:198:18)
    19834 verbose stack     at result.then (/usr/lib/node_modules/npm/lib/install/actions.js:77:25)
    19834 verbose stack From previous event:
    19834 verbose stack     at withInit (/usr/lib/node_modules/npm/lib/install/actions.js:132:15)
    19834 verbose stack     at runCallback (timers.js:785:20)
    19834 verbose stack From previous event:
    19834 verbose stack     at withInit (/usr/lib/node_modules/npm/lib/install/actions.js:182:13)
    19834 verbose stack     at doParallel (/usr/lib/node_modules/npm/lib/install/actions.js:131:10)
    19834 verbose stack     at Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    19834 verbose stack     at LOOP (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    19834 verbose stack     at /usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
    19834 verbose stack     at next (/usr/lib/node_modules/npm/node_modules/rimraf/rimraf.js:75:7)
    19834 verbose stack     at CB (/usr/lib/node_modules/npm/node_modules/rimraf/rimraf.js:111:9)
    19834 verbose stack     at /usr/lib/node_modules/npm/node_modules/rimraf/rimraf.js:137:14
    19834 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:284:29
    19834 verbose stack     at FSReqWrap.oncomplete (fs.js:153:21)
    19835 verbose cwd /home/miles/blockstack-todos
    19836 verbose Linux 4.13.8-1-ARCH
    19837 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
    19838 verbose node v8.7.0
    19839 verbose npm  v5.5.1
    19840 error path /home/miles/blockstack-todos/node_modules/.staging/blockstack-05ae9f0d/node_modules/JSONStream
    19841 error code ENOENT
    19842 error errno -2
    19843 error syscall rename
    19844 error enoent ENOENT: no such file or directory, rename '/home/miles/blockstack-todos/node_modules/.staging/blockstack-05ae9f0d/node_modules/JSONStream' -> '/home/miles/blockstack-todos/node_modules/.staging/JSONStream-a0c1e476'
    19845 error enoent This is related to npm not being able to find a file.
    19846 verbose exit [ -2, true ]

**Comment by MaYuan0117** [comment]
Hi I think I met the problem like u! Do u solve the problem and how? 
<img width="269" alt="_20180113210739" src="https://user-images.githubusercontent.com/31557681/34906299-cf97cd5c-f8a5-11e7-9fe1-c85b28d7b252.png">

**Comment by pstan26** [comment]
@jackzampolin any idea whats happening here and how we can solve? cc  @shea256

**Comment by jackzampolin** [comment]
Upgrade your node version to 6.x. That should fix this issue.
