### ISSUE TITLE
Todos are lost on page refresh

### ISSUE THREAD

**Issue by jay-hwang** [blockstack/blockstack-todos#2]
The todo list disappears when the page is refreshed. Is the app not saving/fetching data properly, or was the todo app just made super simple to not persist any data.

**Comment by pstan26** [comment]
Hmm, this shouldn't happen cc @larrysalibra

**Comment by larrysalibra** [comment]
@jay-hwang @pstan26 Do the todos appear if you log in with another browser? or log out, clear your the local browser state for the origin of the todo app and log in again? They do for me - which shows that state is being persisted in Blockstack Storage.

Todo list data is currently loaded when the Dashboard component's `mounted()` is called. I'm not that familiar with the lifecycle of vue.js apps and whether or not that function is called when you manually refresh the browser. That is to say it is entirely possible that the todo list data is only loaded at log in and not if you refresh the browser while already logged in. 

@jay-hwang Do you want to take a stab at debugging this?

**Comment by jay-hwang** [comment]
I had login issues, so the app didn't have access to my Blockstack storage. Everything is fixed now - I can login and the app persists data. Closing!

**Comment by jay-hwang** [comment]
I lied - everything is not fixed yet. When I first signed in to my new account yesterday, an `index` directory was created in my `Dropbox/Apps/Blockstack` directory, along with a bunch of files named from 0-9, a-f, and an `index.manifest` file. Since I was finally able to log in again and data was written to my Dropbox, I figured the storage was working, but I figured wrong. 

I couldn't get storage to work on the blogging app, so I watched the Todo App tutorial, cloned [Blockstack Todo](https://github.com/blockstack/blockstack-todos), ran yarn install and signed in with my new Blockstack account. Everything was fine and no errors were thrown up to this point. But when trying to create/edit todos or whenever `getFile` or `putFile` is called, the app complains saying it's receiving `null` where it expects `true`, and the data doesn't persist to Dropbox. 

I don't have a username on my new account yet (not sure if this is the cause, but I'm hoping it's something this simple). I bought more Bitcoin yesterday, so I'm going to buy a username once I receive the Bitcoin, then try it again. 

Here's the app screen: 

<img width="1094" alt="screen shot 2017-07-11 at 2 56 29 pm" src="https://user-images.githubusercontent.com/20843566/28092855-c552a8c4-6649-11e7-86d6-14d90c48d4be.png">


And the error message: 

```

vue.esm.js?65d7:523 AssertionError {name: "AssertionError", actual: null, expected: true, operator: "==", message: "null == true"…}actual: nullexpected: truegeneratedMessage: truemessage: "null == true"name: "AssertionError"operator: "=="stack: "AssertionError: null == true↵    at getSessionBlockchainID (eval at <anonymous> (http://localhost:8080/app.js:2448:1), <anonymous>:697:4)↵    at putFile (eval at <anonymous> (http://localhost:8080/app.js:2448:1), <anonymous>:1578:23)↵    at Object.putFile (eval at <anonymous> (http://localhost:8080/app.js:2588:1), <anonymous>:30:41)↵    at VueComponent.handler (eval at <anonymous> (http://localhost:8080/app.js:2359:1), <anonymous>:25:27)↵    at Watcher.run (eval at <anonymous> (http://localhost:8080/app.js:1086:1), <anonymous>:2863:19)↵    at flushSchedulerQueue (eval at <anonymous> (http://localhost:8080/app.js:1086:1), <anonymous>:2616:13)↵    at Array.eval (eval at <anonymous> (http://localhost:8080/app.js:1086:1), <anonymous>:656:14)↵    at nextTickHandler (eval at <anonymous> (http://localhost:8080/app.js:1086:1), <anonymous>:603:16)↵    at <anonymous>"__proto__: Errorconstructor: function AssertionError(options)super_: function Error()arguments: (...)caller: (...)length: 1name: "AssertionError"prototype: Error__proto__: function ()apply: function apply()arguments: (...)bind: function bind()call: function call()caller: (...)constructor: function Function()length: 0name: ""toString: function toString()Symbol(Symbol.hasInstance): function [Symbol.hasInstance]()get arguments: function ThrowTypeError()set arguments: function ThrowTypeError()get caller: function ThrowTypeError()set caller: function ThrowTypeError()__proto__: Object[[FunctionLocation]]: <unknown>[[FunctionLocation]]: assert.js?9281:123[[Scopes]]: Scopes[3]0: Closure1: Closure2: Global__proto__: Object
handleError @ vue.esm.js?65d7:523
run @ vue.esm.js?65d7:2864
flushSchedulerQueue @ vue.esm.js?65d7:2615
(anonymous) @ vue.esm.js?65d7:655
nextTickHandler @ vue.esm.js?65d7:602
```

**Comment by larrysalibra** [comment]
@jay-hwang storage is currently broken without a username. There issue for this is: https://github.com/blockstack/blockstack-browser/issues/609

**Comment by jay-hwang** [comment]
@larrysalibra 

Got a username but the same assertion error is still being thrown. 

Thought maybe my code was wrong so I started up the todo app and tried to make some todos but the assertion error gets thrown there too. Storage clearly works in the todo-tutorial video, so I don't know why this error is so persistent. 

I really want to get storage up and running so I can finish the decentralized blogging app. Any ideas on what I can do? It's getting stuck trying to `getSessionBlockchainID`

```
AssertionError {name: "AssertionError", actual: null, expected: true, operator: "==", message: "null == true"…}
actual : null
expected : true
generatedMessage : true
message : "null == true"
name : "AssertionError"
operator : "=="
stack : "AssertionError: null == true↵    at getSessionBlockchainID (eval at <anonymous> (http://localhost:8080/app.js:2448:1)
```

**Comment by jay-hwang** [comment]
I upgraded Blockstack Browser to v 11 and it works fine now! I'm so stoked!!! It created todos in my Dropbox! This is so cool! Feel like a kid on Christmas

**Comment by larrysalibra** [comment]
@jay-hwang That's great! I had the same feeling! It's so magical when it works :-D
