### ISSUE TITLE
Refresh design and add share option

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack-todos#40]
Refresh the app's UI and aesthetics per [this design spec](https://www.figma.com/file/Edt4xQgxC8Q1fM87qsn1Jy/Tutorials-and-sample-apps), maintaining all current functionality while adding an option to make all tasks public and share a URL for viewing them.

**Comment by markmhx** [comment]
@jasperjansz is going to update the sharing UX so that the prompt to share and URL are always visible once the tasks have been made public.

**Comment by hstove** [comment]
Thanks @timstackblock I had to publish a new version to NPM with a recent fix for that. You should be able to try again, now.

**Comment by markmhx** [comment]
@hstove The design spec should be complete now. Let's get this on staging by EOD Friday so we have a buffer for testing ahead of the release next week on Tuesday?

**Comment by markmhx** [comment]
The README could use some updating while you're in there since the commands listed currently (e.g. `npm run serve`) don't work.

**Comment by markmhx** [comment]
Some enhancements:

- [ ] Automatically save new todos upon typing new characters, not when enter key hit
- [ ] Initiate new todo when user hits enter on any existing todo
- [ ] Show 404 page if user tries to load private list of own or another user at URL with username (currently it shows dummy todo data)
- [ ] Change placeholder copy from "Write your first to do" to "Write new to-do" 
– [ ] Change placeholder copy to `placeholder` value instead of input value

**Comment by jasperjansz** [comment]
I don't think we should save new todos upon typing new characters. That sounds needlessly complicated.

Here's my feedback:

- I think the initial state should be autofocused on the first line with placeholder copy, like this: https://www.figma.com/file/Edt4xQgxC8Q1fM87qsn1Jy/Tutorials-and-sample-apps?node-id=2%3A893
- I think it's unintuitive to have to focus a checked-off item and then hit enter to add another, see attachment. We could do this instead: https://www.figma.com/file/Edt4xQgxC8Q1fM87qsn1Jy/Tutorials-and-sample-apps?node-id=106%3A123.


![image](https://user-images.githubusercontent.com/25477905/85398509-9f703500-b555-11ea-9ff1-16a2111b63bc.png)

**Comment by markmhx** [comment]
> I don't think we should save new todos upon typing new characters. That sounds needlessly complicated.

This is how Asana works and it's quite smooth. Basically gives the sensation that whatever you see as the state on screen is exactly what's saved. There's no extra step.

> I think it's unintuitive to have to focus a checked-off item and then hit enter to add another, see attachment

Is the idea here that "Add another" shows up always? What happens when I select it and start typing, does another appear?

**Comment by markmhx** [comment]
Here's a little sample of the Asana interactions for reference:

![ezgif-4-560ec5fc0254](https://user-images.githubusercontent.com/28991/85399381-06dab480-b557-11ea-98d3-d0c2a4e2b3cf.gif)

**Comment by hstove** [comment]
I think we shouldn't auto-save on every character. For one, the user will probably hit a rate limit - I think you're only allowed something like 25 calls per minute on Gaia?

**Comment by markmhx** [comment]
@hstove It sounds like from our Slack convo with Alex that the only thing that remains here is to deploy the app to https://todos.blockstack.org/?
