### ISSUE TITLE
Host app for documentation

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack-todos#41]
We should host this app somewhere so we can easily link to it from documentation for readers who want to try it out before installing locally.

@agraebe @hstove @johndmulhausen Thoughts on the URL we should use? docs.blockstack.com/apps/todos, todos.blockstack.org or something else?

**Comment by agraebe** [comment]
Long-term, I'd love to have a suite of sample apps that match the main use cases we advertise on our homepage. Maybe a consistent path for future sample apps would make sense? Something like `samples.blockstack.org/<app_name>`? That way, the landing page could also have a tiny index/overview of sample apps.

**Comment by markmhx** [comment]
@hstove Should we contact devops about this now to get it hosted by EOD on Monday?
