### ISSUE TITLE
deneme

### ISSUE THREAD

**Issue by Bulent1** [blockstack/blockstack-todos#49]
// src/components/Signin.jsx

import { useConnect } from '@blockstack/connect';

export const Signin = () => {
  const { doOpenAuth } = useConnect();

  return <Button onClick={() => doOpenAuth()}>Get Started</Button>;
};

**Comment by kyranjamie** [comment]
Can you elaborate on this issue @Bulent1 ?

**Comment by agraebe** [comment]
I compared to the implementation and it looks like the request is to remove the boxing / design boilerplate? would close because this would screw up the UI. @Bulent1 please re-open with clarification if there's more to it.
